Intro to numpy

Tutorial: https://www.tutorialspoint.com/numpy/index.htm

Manual: https://docs.scipy.org/doc/numpy/index.html

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
import numpy as np # importa numpy

a = np.array([[1, 2, 3], [4, 5, 6]]) # crea un array de numpy

a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# cortar columnas y subarrays

b = a[:,0] # corta primera columna, pero como vector fila
b

c = a[:,[0]] # corta primera columna, pero como vector columna
c

array([1, 4])

array([[1],
       [4]])

In [5]:
# componer nuevos arrays a partir de partes de los ya existentes

np.hstack((c, a, c))

array([[1, 1, 2, 3, 1],
       [4, 4, 5, 6, 4]])

In [6]:
# operaciones con matrices

np.transpose(a) # transpone matriz
a

np.dot(a,np.transpose(a))

array([[1, 4],
       [2, 5],
       [3, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[14, 32],
       [32, 77]])

In [12]:
# Carga de ficheros de datos
X = np.loadtxt('iris.csv',dtype = 'float64',usecols = [0,1,2,3])
L = np.loadtxt('iris.csv',dtype = str,usecols = [4]) 

d = []
options = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
for e in L:
    d.append(options.index(e))


In [44]:
# Ua cosa importante de numpy es que todas sus operaciones definidas sobre escalares funcionan también sobvre vectores

def sigm (neta):
        return 1.0 / (1.0 + np.exp(-neta))
    
sigm(1.0)

v = np.array([0.0, 0.5, 1.0])
sigm(v)

# pero, ojo, no funcionaría sobre una lista; tiene que ser un array de numpy

0.7310585786300049

array([0.5       , 0.62245933, 0.73105858])

In [45]:
# números aleatorios

np.random.rand(5,5)

array([[0.59308549, 0.80697622, 0.82674778, 0.17789891, 0.72670514],
       [0.33927414, 0.3851305 , 0.84584314, 0.55528763, 0.19805892],
       [0.57807604, 0.23760809, 0.83944648, 0.55949194, 0.52520068],
       [0.72830501, 0.14242442, 0.21669521, 0.97280744, 0.6835506 ],
       [0.4794484 , 0.63780926, 0.07739814, 0.11646947, 0.09949443]])

In [46]:
# obtener y cambiar las dimensiones de una matriz (se usa mucho en redes de neuronas)

a

np.shape(a)


array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

In [48]:
a.reshape(3,2) # ojo, no es transponer

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a = a.reshape(6,1)

In [14]:
# convertir un array en un vector
# es útil para convertir arrays unidimensionales en vectores y no preocuparnos por sus dimensiones, 
# ya que podemos multiplicar siempre vectores por matrices si el bnúmero de elementos es correcto
# además, el resultado de una matriz por un vector es siempre un vector

v = a.flatten()
v

m = np.random.rand(6,2)
m

v.dot(m)


m.transpose().dot(v)


array([1, 2, 3, 4, 5, 6])

array([[0.14284721, 0.27794633],
       [0.80587913, 0.54329628],
       [0.21183155, 0.43202568],
       [0.52957646, 0.97335747],
       [0.56685476, 0.72340497],
       [0.96641102, 0.43041306]])

array([13.14114593, 12.75354903])

array([13.14114593, 12.75354903])

In [52]:
# otra cuestión interesante es que dot puede usarse como operando o como método

np.dot(v,m)

# equivale a

v.dot(m)

# la ventaja de la primera forma es que puede usarse con listas de python además de con estructuras de numpy

np.dot([1, 2, 3, 4, 5, 6],m)

np.dot([1, 2],[[1, 1, 1],[2, 3, 4]])



array([8.70664497, 4.18837378])

array([8.70664497, 4.18837378])

array([8.70664497, 4.18837378])

array([5, 7, 9])

In [53]:
# otra cosa importante de numpy es que cualquier función se puede aplicar sobre escalares o tensores

np.sin(v)

np.sin(m)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

array([[0.44759508, 0.83995962],
       [0.01135496, 0.00676645],
       [0.09271518, 0.12653232],
       [0.15765033, 0.41316186],
       [0.34999048, 0.19146392],
       [0.79562857, 0.02167396]])